services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      network: host
    ports:
      - '3000:3000'
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/distribuidora
      - AUTH_SECRET=supersecret-change-in-production
      - AUTH_URL=https://noop.tail617ede.ts.net
      - COSMOS_API_TOKEN=KZpxzMef-dp5QH5uvSs5Dw
    depends_on:
      db:
        condition: service_healthy
    restart: unless-stopped

  db:
    image: postgres:15-alpine
    ports:
      - '5436:5432'
    environment:
      POSTGRES_DB: distribuidora
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres']
      interval: 5s
      timeout: 5s
      retries: 5
    restart: unless-stopped

volumes:
  pgdata:
